title: daanbreur
url: https://blog.daanbreur.systems
author: daanbreur
description: Hey, I am Daan. A programmer and hacker.

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: daanbreurblog

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/portaalg
      icon: twitter
      color: cyan
    - url: https://www.twitch.tv/portaalgaming
      icon: twitch
      color: purple
    - url: https://www.youtube.com/channel/UCGWs9foruVqIoEf2sLBfJAg
      icon: youtube
      color: red
    - url: https://github.com/daanbreur
      icon: github
      color: yellow

# Build settings
# theme: jekyll-dash

plugins:
  - liquid-md5
  - jekyll/tagging


# Replaces the default avatar provider (gravatar)
avatar_source: github
github_username: daanbreur
