remote_theme: CaptainIRS/hacker-plus-theme

title: Daanbreurs Blog
author: daanbreur
description: Daanbreurs Blog for CTF Writeups and More
google_site_verification_content: # The 'content' tag for site verification
google_analytics: # Your Google Analytics Tracking ID
disqus_forum_shortname: daanbreurblog

# Usernames and badges
htb_badge_no: # Go to the HackTheBox site and copy your ID
thm_badge_no: 34192
show_thm_htb_badges_in_nav: false
github_username: daanbreur
stackoverflow: users/10564495
twitch: portaalgaming
twitter: portaalg
reddit: daandevelopment


# -------DO NOT ALTER -------#
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
exclude: [
   /*/*/_problems/*,
   scripts
]
plugins:
   - jekyll-seo-tag
   - jemoji
   - jekyll-sitemap
   - jekyll-github-metadata
collections:
   pages:
      output: true
      permalink: /:name
   writeups:
      output: true 
   blog:
      output: true